### ISSUE TITLE
Solidity multidimensional array as return

### ISSUE THREAD

**Issue by ismoli** [hyperledger/web3j#2038]
# _Bug_title_
Impossible to call Solidity function that returns 2d array from contract

## Steps To Reproduce
Simple solidity function:
`
 function get() view external returns (uint128[][] memory) {...}
`
Generate wrapper, or construct ethCall manually.

### Expected behavior
Function should be called successfully and return result

### Actual behavior
Exception occurred
```
java.lang.UnsupportedOperationException: Unable to access parameterized type org.web3j.abi.datatypes.DynamicArray<org.web3j.abi.datatypes.DynamicArray<org.web3j.abi.datatypes.generated.Uint128>>

	at org.web3j.abi.TypeDecoder.decodeArrayElements(TypeDecoder.java:694)
	at org.web3j.abi.TypeDecoder.decodeDynamicArray(TypeDecoder.java:442)
	at org.web3j.abi.DefaultFunctionReturnDecoder.build(DefaultFunctionReturnDecoder.java:100)
	at org.web3j.abi.DefaultFunctionReturnDecoder.decodeFunctionResult(DefaultFunctionReturnDecoder.java:52)
	at org.web3j.abi.FunctionReturnDecoder.decode(FunctionReturnDecoder.java:57)
	at org.web3j.tx.Contract.executeCall(Contract.java:313)
	at org.web3j.tx.Contract.executeCallMultipleValueReturn(Contract.java:357)

```

## Environment
Web3j version 4.9.8

## Additional context
So generated code is using 
`
new TypeReference<DynamicArray<DynamicArray<Uint128>>>() {}
` as output value which seems like not really working.

Is there any workaround? When constructing a call manually (as opposed to generating wrapper), what should I set for Types to 'Output parameters' to make it work?

**Comment by alexdupre** [comment]
I've just encountered another issue with multi-dimensional arrays as return value, but with the opposite generated code.

For a function defined as
```
function getStateOfRewards(address _rewardOwner) external view returns (RewardState[][] memory rewardStates);
```

the generated wrapper was:

```
final Function function = new Function(FUNC_GETSTATEOFREWARDS, 
                Arrays.<Type>asList(new org.web3j.abi.datatypes.Address(160, _rewardOwner)), 
                Arrays.<TypeReference<?>>asList(new TypeReference<DynamicArray<RewardState>>() {}));
```

that didn't work because of the missing nested array. Changing it to:

```
final Function function = new Function(FUNC_GETSTATEOFREWARDS, 
                Arrays.<Type>asList(new org.web3j.abi.datatypes.Address(160, _rewardOwner)), 
                Arrays.<TypeReference<?>>asList(new TypeReference<DynamicArray<DynamicArray<RewardState>>>() {}));
```

made it working.

Tested with today 4.12.0-SNAPSHOT.

**Comment by kxl4126** [comment]
The `getTypeAsString` for `DynamicArray` only supports `DynamicStruct` as a nested type. I just created another class extending DynamicArray and overrode it so it also supported `DynamicArray` as a nested type like:
```
override fun getTypeAsString(): String {
        val type = if (value.isEmpty()) {
            if (StructType::class.java.isAssignableFrom(this.componentType)) {
                Utils.getStructType(this.componentType)
            } else {
                AbiTypes.getTypeAString(this.componentType)
            }
        } else if (StructType::class.java.isAssignableFrom((value[0] as Type<*>).javaClass) || (DynamicArray::class.java.isAssignableFrom((value[0] as Type<*>).javaClass))) {
            (value[0] as Type<*>).typeAsString
        } else {
            AbiTypes.getTypeAString(this.componentType)
        }

        return "$type[]"
    }
    ```
    This worked for me, at least for nested arrays.

**Comment by FangshuoCao** [comment]
Hi @ismoli , Could you provide more detail to reproduce the problem?

I tested the issue using a simple contract with this method:
```
function get() external view returns (uint128[][] memory) {
        uint n = matrix.length;
        uint128[][] memory out = new uint128[][](n);
        for (uint i = 0; i < n; i++) {
            uint m = matrix[i].length;
            uint128[] memory row = new uint128[](m);
            for (uint j = 0; j < m; j++) {
                row[j] = matrix[i][j];
            }
            out[i] = row;
        }
        return out;
    }
```

The method in the generated contract wrapper is this: 
```
public RemoteFunctionCall<List> get() {
        final Function function = new Function(FUNC_GET, 
                Arrays.<Type>asList(), 
                Arrays.<TypeReference<?>>asList(new TypeReference<DynamicArray<DynamicArray<Uint128>>>() {}));
        return new RemoteFunctionCall<List>(function,
                new Callable<List>() {
                    @Override
                    @SuppressWarnings("unchecked")
                    public List call() throws Exception {
                        List<Type> result = (List<Type>) executeCallSingleValueReturn(function, List.class);
                        return convertToNative(result);
                    }
                });
    }
```
Using this generated get() method, I was able to get the nested array correctly(using either Web3j 4.9.8 or the latest 4.14.0)

**Comment by FangshuoCao** [comment]
Hi @kxl4126, Could you provide an example of the problem you mentioned?
From my understanding the current getTypeAsString() method works fine with nested DynamicArray, since this test can pass:
`@Test
    public void testMultidimensionalDynamicArray() {
        DynamicArray<DynamicArray> array =
                new DynamicArray<>(
                        DynamicArray.class,
                        List.of(
                                new DynamicArray<>(
                                        DynamicArray.class,
                                        List.of(
                                                new DynamicArray<>(
                                                        Uint256.class, new ArrayList<>())))));
        assertEquals("uint256[][][]", array.getTypeAsString());
    }`
