### ISSUE TITLE
Error sending request

### ISSUE THREAD

**Issue by yuehaidong** [hyperledger/web3j#2103]
2024-09-26 09:05:43.934 ERROR 16571 --- [pool-8-thread-4] org.web3j.protocol.core.filters.Filter : Error sending request

org.java_websocket.exceptions.WebsocketNotConnectedException: null
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608) ~[Java-WebSocket-1.3.8.jar!/:na]
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585) ~[Java-WebSocket-1.3.8.jar!/:na]
at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:309) ~[Java-WebSocket-1.3.8.jar!/:na]
at org.web3j.protocol.websocket.WebSocketService.sendRequest(WebSocketService.java:235) ~[core-4.8.7.jar!/:na]
at org.web3j.protocol.websocket.WebSocketService.sendAsync(WebSocketService.java:186) ~[core-4.8.7.jar!/:na]
at org.web3j.protocol.websocket.WebSocketService.send(WebSocketService.java:165) ~[core-4.8.7.jar!/:na]
at org.web3j.protocol.core.Request.send(Request.java:87) ~[core-4.8.7.jar!/:na]
at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:129) ~[core-4.8.7.jar!/:na]
at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:92) ~[core-4.8.7.jar!/:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_371]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_371]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_371]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_371]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_371]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_371]
at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_371]

This is my exception error. I want to listen for the transfer event, but when this exception occurs, the listening becomes invalid. I am using version 4.8.7, will upgrading to 5.0.0 solve it

**Comment by dev-wasabi** [comment]
Were you able to find a solution for this?

**Comment by yuehaidong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
